services:
  portfolio-app:
    image: bravojonasco/portfolio-app:latest
    container_name: portfolio-app
    ports:
      - "5000:80"
    restart: unless-stopped

  flask-app:
    image: bravojonasco/flask-app:latest
    container_name: flask-app
    ports:
      - "5001:5000"
    restart: unless-stopped

  java-web-app:
    image: bravojonasco/java-web-app:latest
    container_name: java-web-app
    ports:
      - "8081:8080"
    restart: unless-stopped

  nginx:
    image: bravojonasco/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "8088:80"
    depends_on:
      - portfolio-app
      - flask-app
      - java-web-app
    restart: always
